/**
 * This software is released as part of the Pumpernickel project.
 * 
 * All com.pump resources in the Pumpernickel project are distributed under the
 * MIT License:
 * https://raw.githubusercontent.com/mickleness/pumpernickel/master/License.txt
 * 
 * More information about the Pumpernickel project is available here:
 * https://mickleness.github.io/pumpernickel/
 */
package com.pump.showcase;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

import com.pump.awt.CalligraphyStroke;
import com.pump.blog.ResourceSample;

/**
 * A simple demo program showing off the {@link com.pump.awt.CalligraphyStroke}.
 * 
 * <!-- ======== START OF AUTOGENERATED SAMPLES ======== -->
 * <p>
 * <img src=
 * "https://raw.githubusercontent.com/mickleness/pumpernickel/master/pump-release/resources/samples/CalligraphyStrokeDemo/sample.png"
 * alt="new&#160;com.pump.awt.CalligraphyStrokeDemo()"> 
 * <!-- ======== END OF AUTOGENERATED SAMPLES ======== -->
 */
@ResourceSample(sample = "new com.pump.awt.CalligraphyStrokeDemo()")
public class CalligraphyStrokeDemo extends StrokeDemo {
	private static final long serialVersionUID = 1L;

	public static void main(String[] args) {
		try {
			CalligraphyStrokeDemo d = new CalligraphyStrokeDemo();
			JFrame f = new JFrame();
			f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
			f.getContentPane().add(d);
			f.pack();
			f.setVisible(true);
		} catch (NoSuchMethodException e) {
			e.printStackTrace();
		}
	}

	public CalligraphyStrokeDemo() throws NoSuchMethodException {
		super(CalligraphyStroke.class, CalligraphyStroke.class
				.getConstructor(new Class[] { Float.TYPE, Float.TYPE }),
				new JLabel[] { new JLabel("Width:"), new JLabel("Angle:") },
				new JSpinner[] {
						new JSpinner(new SpinnerNumberModel(15, .05, 30, .1)),
						new JSpinner(new SpinnerNumberModel(1, 0, 2 * Math.PI,
								.05)), });
	}
}