/**
 * This software is released as part of the Pumpernickel project.
 * 
 * All com.pump resources in the Pumpernickel project are distributed under the
 * MIT License:
 * https://raw.githubusercontent.com/mickleness/pumpernickel/master/License.txt
 * 
 * More information about the Pumpernickel project is available here:
 * https://mickleness.github.io/pumpernickel/
 */
package com.pump.showcase;

import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

import com.pump.awt.CharcoalStroke;
import com.pump.blog.Blurb;
import com.pump.blog.ResourceSample;

/** A simple demo program showing off the {@link com.bric.awt.CharcoalStroke}.
 * 
 * 
 * <!-- ======== START OF AUTOGENERATED SAMPLES ======== -->
 * <p><img src="https://javagraphics.java.net/resources/samples/CharcoalStrokeDemo/sample.png" alt="new&#160;com.bric.awt.CharcoalStrokeDemo()">
 * <!-- ======== END OF AUTOGENERATED SAMPLES ======== -->
 */
@Blurb (
filename = "CharcoalStroke",
title = "Strokes: a Charcoal Stroke",
releaseDate = "December 2008",
summary = "A stroke with grooves in the edges that resembles charcoal on pavement.\n"+
"<P>This stroke is actually a filter than can modify any shape, but the only "+
"current suitable examples are <code>BasicStrokes</code> and <code>CalligraphyStrokes</code>.",
instructions = "This applet showcases a stroke that chips away at a BasicStroke with thousands of "+
"carefully placed cracks.\n"+
"<p>Use the three spinners to control the width, crack size, and crack angle of the stroke. There is blue text on the preview "+
"that displays the time it took to render everything.",
link = "http://javagraphics.blogspot.com/2008/12/strokes-charcoal-stroke.html",
sandboxDemo = true
)
@ResourceSample( sample="new com.bric.awt.CharcoalStrokeDemo()" )
public class CharcoalStrokeDemo extends StrokeDemo {
	private static final long serialVersionUID = 1L;
	
	public CharcoalStrokeDemo() throws NoSuchMethodException {
		super(CharcoalStroke.class, CharcoalStroke.class.getConstructor(new Class[] {
			Float.TYPE,
			Float.TYPE,
			Float.TYPE
		}),
		new JLabel[] {
			new JLabel("Starting Width:"),
			new JLabel("Crack Size:"),
			new JLabel("Crack Angle:"),
		},
		new JSpinner[] {
			new JSpinner(new SpinnerNumberModel(1,.05,20,.1)),
			new JSpinner(new SpinnerNumberModel(.45,0,1,.05)),
			new JSpinner(new SpinnerNumberModel(0,0,2*Math.PI,.1))
		});
	}
}