/**
 * This software is released as part of the Pumpernickel project.
 * 
 * All com.pump resources in the Pumpernickel project are distributed under the
 * MIT License:
 * https://raw.githubusercontent.com/mickleness/pumpernickel/master/License.txt
 * 
 * More information about the Pumpernickel project is available here:
 * https://mickleness.github.io/pumpernickel/
 */
package com.pump.showcase;

import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

import com.pump.awt.CharcoalStroke;
import com.pump.blog.Blurb;
import com.pump.blog.ResourceSample;

/** A simple demo program showing off the {@link com.pump.awt.CharcoalStroke}.
 * 
 * 
 * <!-- ======== START OF AUTOGENERATED SAMPLES ======== -->
 * <p><img src="https://raw.githubusercontent.com/mickleness/pumpernickel/master/pump-release/resources/samples/CharcoalStrokeDemo/sample.png" alt="new&#160;com.bric.awt.CharcoalStrokeDemo()">
 * <!-- ======== END OF AUTOGENERATED SAMPLES ======== -->
 */
@ResourceSample( sample="new com.bric.awt.CharcoalStrokeDemo()" )
public class CharcoalStrokeDemo extends StrokeDemo {
	private static final long serialVersionUID = 1L;
	
	public CharcoalStrokeDemo() throws NoSuchMethodException {
		super(CharcoalStroke.class, CharcoalStroke.class.getConstructor(new Class[] {
			Float.TYPE,
			Float.TYPE,
			Float.TYPE
		}),
		new JLabel[] {
			new JLabel("Starting Width:"),
			new JLabel("Crack Size:"),
			new JLabel("Crack Angle:"),
		},
		new JSpinner[] {
			new JSpinner(new SpinnerNumberModel(1,.05,20,.1)),
			new JSpinner(new SpinnerNumberModel(.45,0,1,.05)),
			new JSpinner(new SpinnerNumberModel(0,0,2*Math.PI,.1))
		});
	}
}