/*
 * @(#)PauseIcon.java
 *
 * $Date: 2014-06-06 14:04:49 -0400 (Fri, 06 Jun 2014) $
 *
 * Copyright (c) 2011 by Jeremy Wood.
 * All rights reserved.
 *
 * The copyright of this software is owned by Jeremy Wood. 
 * You may not use, copy or modify this software, except in  
 * accordance with the license agreement you entered into with  
 * Jeremy Wood. For details see accompanying license terms.
 * 
 * This software is probably, but not necessarily, discussed here:
 * https://javagraphics.java.net/
 * 
 * That site should also contain the most recent official version
 * of this software.  (See the SVN repository for more details.)
 */
package com.pump.icon;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Rectangle2D;

import javax.swing.Icon;

import com.pump.blog.ResourceSample;

/** A pause icon.
 * 
 * <!-- ======== START OF AUTOGENERATED SAMPLES ======== -->
 * <p><img src="https://javagraphics.java.net/resources/samples/PauseIcon/sample.png" alt="new&#160;com.bric.swing.resources.PauseIcon(&#160;24,&#160;24,&#160;java.awt.Color.lightGray)">
 * <!-- ======== END OF AUTOGENERATED SAMPLES ======== -->
 *
 * @see FirstIcon
 * @see LastIcon
 */
@ResourceSample( sample= { "new com.bric.swing.resources.PauseIcon( 24, 24, java.awt.Color.lightGray)" })
public class PauseIcon implements Icon {
	
	int width, height;
	Color color;

	public PauseIcon(int w,int h) {
		this(w, h, Color.darkGray);
	}
	
	public PauseIcon(int w,int h,Color color) {
		if(color==null) throw new NullPointerException();
		width = w;
		height = h;
		this.color = color;
	}

	public int getIconHeight() {
		return height;
	}

	public int getIconWidth() {
		return width;
	}

	public void paintIcon(Component c, Graphics g, int x, int y) {
		float barWidth = width*2/5;
		Graphics2D g2 = (Graphics2D)g;
		g2.setColor(color);
		g2.fill(new Rectangle2D.Float(x, y, barWidth, height));
		g2.fill(new Rectangle2D.Float(x+width-barWidth, y, barWidth, height));
	}

}
